### ISSUE TITLE
Melhorar retorno de erros da `API`

### ISSUE THREAD

**Issue by FSLucas22** [hywenklis/buddy-api#136]
### Contexto
Na PR #124, foram criadas diversas validações relacionadas à criação de perfil. O problema é que no momento em que uma violação é detectada, uma `DomainException` é lançada e o erro é reportado. Isso significa que em uma situação em que diversas violações ocorrerem ao mesmo tempo, somente uma delas será reportada.

Penso que esse problema será recorrente nos `endpoints de cadastro`, quanto mais eles envolverem outras entidades do sistema, mais coisas terão que ser verificadas.

### O que precisa ser feito?
Assim proponho:

- [ ] a criação de classes `validadoras` que performam diversas validações e retornam todas as violações encontradas (de forma similar aos erros de `MethodArgumentNotValidException` que possuem os `bindingResults`.
- [ ] refatoração dos serviços para delegar suas respectivas validações para as classes `validadoras`
Como consequência dessa abordagem:
- [ ] algumas classes de erro que hoje são relacionadas à um mesmo `service` deverão ser abstraídas em uma classe de erro mais genérica. 
    exemplo: Ao invés de haver um `InvalidProfileTypeException` e um `ProfileNameAlreadyRegisteredException`, o `validador` lançaria um `ProfileException`, ou um `DomainValidationException`, ou talvez simplesmente a própria `DomainException`.

Não coloquei essas mudanças juntamente com a PR #124 pois penso que o assunto supera o escopo dela e também merece uma discussão de como será implementado (se for implementado).

### Vantagens
Isso permitira que o usuário soubesse diversas coisas que precisam ser corrigidas com seu pedido de uma única vez, diminuindo a necessidade de fazer vários `requests`.

**Comment by genesluna** [comment]
Pelo que eu entendi, ele está sugerindo algo similar à `notification pattern`. 

[Notification Pattern](https://medium.com/tableless/n%C3%A3o-lance-exceptions-em-seu-dom%C3%ADnio-use-notifications-70b31f7148d3)

**Comment by hywenklis** [comment]
Vi o artigo sobre notification pattern que você enviou @genesluna. Eu entendo o valor, especialmente em cenários onde múltiplas validações precisam ser reportadas simultaneamente. No entanto, acredito que ele é mais adequado para validações na camada de request, onde o objetivo principal é apontar inconsistências no formato ou nos dados enviados pelo cliente.

No domínio, prefiro seguir com exceções específicas para cada regra de negócio violada. Isso proporciona:

**Maior clareza:** Exceções específicas facilitam identificar qual regra do domínio foi quebrada e refletem com precisão o significado da violação.

**Aderência ao DDD:** Lançar exceções que representam conceitos do domínio mantém a lógica de negócio encapsulada e alinhada aos seus invariantes.

**Segurança e integridade:** Diferentemente das validações de request, as regras de negócio podem depender de múltiplos estados e contextos. Evitar executar toda a lógica para descobrir todas as violações ajuda a prevenir estados inconsistentes.

Sobre a possibilidade de criar uma lista de erros, vejo um bom potencial, mas apenas para validações de request. O Spring já facilita isso com o suporte ao Bean Validation e a captura de **MethodArgumentNotValidException**. É possível interceptar essa exceção, extrair todos os erros dos BindingResults e retorná-los de forma estruturada em um único response. Isso atende ao objetivo de informar o cliente sobre múltiplos problemas sem interferir na camada de domínio.

Por outro lado, tentar unificar erros de request e de domínio em um único fluxo pode introduzir complexidade desnecessária. Cada camada do sistema tem responsabilidades distintas e abordagens diferentes para lidar com erros fazem mais sentido nesse contexto.

Com essa separação entdo que:

**Request:** Usa Spring Validation para validações simples e retorna todos os erros simultaneamente.
**Domínio:** Lança exceções específicas e foca em garantir que o estado do sistema esteja sempre consistente.

Faz sentido? Caso não seja isso que entendi, gostaria de mais contexto.

**Comment by FSLucas22** [comment]
> Pelo que eu entendi, ele está sugerindo algo similar a `notification pattern`.
> 
> [Notification Pattern](https://medium.com/tableless/n%C3%A3o-lance-exceptions-em-seu-dom%C3%ADnio-use-notifications-70b31f7148d3)

@genesluna Perfeito! A essência da ideia é exatamente essa: Acumular todas as violações de validações e reportar de uma vez.

Para o nosso caso específico, já temos o `Rest Controller Advice` que lida com fluxos de erro da `API`, então ao invés de uma classe extra de validação, acho que fica mais simples, pelo menos de momento, reutilizá-lo. Seria o caso conforme o artigo cita como possibilidade, de no final lançar uma única exceção caso a validação tenha sido encontrada. Eu percebo o valor de simplesmente ter um `NotificationContext` separado que simplesmente guarda todas as notificações. Por exemplo: Em um contexto onde múltiplos serviços se comunicam entre si realizando validações, ele facilitaria muito a ideia de acumular todas as violações, ao invés de lançar uma exceção. Mas por enquanto, acredito que é mais simples simplesmente reaproveitarmos o `Rest Controller Advice`.

Da forma que eu pensei, funcionaria assim:

```mermaid
classDiagram
CreateProfile *-- ProfileValidator
ProfileValidator --> DomainException : Throws
class ProfileValidator {
    +validate(ProfileDto)
}
class CreateProfile {
    +create(ProfileDto)
}
class DomainException {
     +getErrorsDetails() List~ErrorDetails~
}
```

> Sobre a possibilidade de criar uma lista de erros, vejo um bom potencial, mas apenas para validações de request. O Spring já facilita isso com o suporte ao Bean Validation e a captura de MethodArgumentNotValidException. É possível interceptar essa exceção, extrair todos os erros dos BindingResults e retorná-los de forma estruturada em um único response. Isso atende ao objetivo de informar o cliente sobre múltiplos problemas sem interferir na camada de domínio.

O proposta que eu fiz do `ProfileValidator` (que é só um exemplo, existiriam validadores para outras classes que necessitarem também) foi visando aproximar da forma que já fazemos hoje nos services, em que colocamos verificações e lançamos a exceção. A diferença nesse caso seria somente ao invés de verificar diretamente, guardaríamos as verficações dentro do `Validator` e usaríamos o método `validate` dele, que lançaria a exceção (que seria pega pelo `Rest Controller Advice`) se algo estivesse errado. 

Mas se é possível fazer pelo `Spring Validation`, podemos fazer também. Acho que o @hywenklis fez algo parecido com a annotation `@Unique`.

**Comment by FSLucas22** [comment]
> Segurança e integridade: Diferentemente das validações de request, as regras de negócio podem depender de múltiplos estados e contextos. Evitar executar toda a lógica para descobrir todas as violações ajuda a prevenir estados inconsistentes.

Pode me dar um exemplo disso que você está falando? Não consegui visualizar muito bem dentro do nosso contexto.

**Comment by genesluna** [comment]
> Vi o artigo sobre notification pattern que você enviou @genesluna. Eu entendo o valor, especialmente em cenários onde múltiplas validações precisam ser reportadas simultaneamente. 

Pelo que entendi, é exatamente esse o nosso cenário.

> No domínio, prefiro seguir com exceções específicas para cada regra de negócio violada. Isso proporciona:
> 
> **Maior clareza:** Exceções específicas facilitam identificar qual regra do domínio foi quebrada e refletem com precisão o significado da violação.

Não vejo que um padrão seja menos claro que o outro. De um lado você tem *custom exceptions* e do outro você tem *custom messages*. 

> **Aderência ao DDD:** Lançar exceções que representam conceitos do domínio mantém a lógica de negócio encapsulada e alinhada aos seus invariantes.

`Notification pattern` é amplamente usada em DDD. Comecei a usar justamente depois que comecei a seguir o DDD. A lógica fica encapsulada no domínio do mesmo jeito. A única diferença é que ao invés de retornar uma exceção  de cada vez, para cada tipo de erro de validação, retornamos um objeto com *domain notifications*.  

> **Segurança e integridade:** Diferentemente das validações de request, as regras de negócio podem depender de múltiplos estados e contextos. Evitar executar toda a lógica para descobrir todas as violações ajuda a prevenir estados inconsistentes.

Não entendo dessa forma. DDD diz que não podemos instanciar uma entidade com dados inválidos. A diferença do jeito que você faz e do jeito que `Notification pattern` faz é que ao invés de ir reportando um problema de cada vez, reporta-se tudo que há de errado de uma vez só.

Outra coisa muito interessante nesse padrão é deixar o uso de *Exceptions* para casos em que de fato haja uma exceção. Regras de negócio, são regras e não exceções.

**Comment by FSLucas22** [comment]
> > > Segurança e integridade: Diferentemente das validações de request, as regras de negócio podem depender de múltiplos estados e contextos. Evitar executar toda a lógica para descobrir todas as violações ajuda a prevenir estados inconsistentes.
> > 
> > 
> > Pode me dar um exemplo disso que você está falando? Não consegui visualizar muito bem dentro do nosso contexto.
> 
> Vou tentar kkk. Vamos supor que estamos tratando a criação de um ProfileEntity e temos as seguintes regras de negócio no domínio:
> 
> O nome do perfil deve ser único para a conta. O tipo de perfil deve ser válido. A conta associada ao perfil deve estar ativa.
> 
> Se decidirmos executar todas as validações antes de lançar as exceções, corremos o risco de expor o sistema a inconsistências. Por exemplo, validar o tipo de perfil antes de verificar se a conta está ativa pode acabar gerando uma consulta ou lógica desnecessária para uma conta que nem deveria permitir operações. Isso pode levar o sistema a avaliar regras sobre dados em estados inválidos ou mesmo expor detalhes internos desnecessários.
> 
> Além disso, em operações que envolvem transações no banco de dados, como gravações ou atualizações, o ideal é detectar o primeiro erro e interromper o fluxo imediatamente. Executar todas as validações de uma vez pode gerar deadlocks (**Resumidamente, um deadlock ocorre quando o banco de dados detecta que 2 processos estão aguardando um pelo outro para continuarem suas atividades.**) ou operações inconsistentes, especialmente se parte das validações depende de interação com outras tabelas ou sistemas externos.
> 
> Por isso, acredito que lançar exceções específicas no momento em que uma violação é detectada mantém o sistema mais seguro e resiliente, evitando estados intermediários problemáticos. É uma forma de garantir que cada erro seja tratado diretamente, sem sobrecarregar o fluxo com listas de validações que podem mascarar problemas mais sérios.

Entendi, pensando num contexto de multiplos acessos ao banco de dados, conforme a quantidade de dados crescer se não formos cuidadosos as transações podem não ser tão rápidas, aumentando assim a chance de deadlocks acontecerem ou simplesmente prejudicar a performance. Mesmo que agora temos pouca comunicação entre os serviços e as coisas são "simples", não há, em teoria, limite para a complexidade que os fluxos podem tomar com o passar do tempo.

Então penso que realmente para o contexto de acesso ao banco de dados ou a outros services (porque esses services talvez consultem o banco também), realmente acho que não devemos acumular os erros. Sobram assim somente os erros de validação de forma dos dados, que já fazemos utilizando o `Jakarta`. Embora exista possibilidade de melhorar isso e colocar validações não somente nos requests, e para este caso o `Notification Pattern` teria um grande valor, no momento essa necessidade ainda não apareceu.

Também, inicialmente havia proposto utilizá-lo (ou algo parecido) reaproveitando o `Rest Controller Advice`, que trabalha com capturando `Exceptions`. Mas não é trivial definir como poderemos mapear todas as violações de validação em um cenário de comunicação entre vários serviços:

Se definirmos que todas as validações serão feitas e só no final de cada chamada a um service é que lançaremos uma exceção, surge então a questão de quem é responsável por lançar a exceção no final do fluxo: Caso isso seja responsabilidade do service, quando o service precisasse se comunicar com outros, teria que capturar exceções lançadas pelos outros para não interromper o fluxo. Essa necessidade de sempre capturar as exceções de outro service causaria uma repetição de código em todo service que tentasse se comunicar com outros. 

Caso isso seja responsabilidade dos controllers, então em todo service teriamos que lembrar de retornar o fluxo mais cedo caso uma violação ocorresse e, no controller, teriamos que lembrar de lançar a exceção, introduzindo uma lógica a mais que depende de duas camadas diferentes.

Assim parece que teria que surgir camada externa responsável pelos fluxos de validações, separando os services em "services de execução" e "services de validação"... Ou outra estratégia. O ponto é: Traria complicações na arquitetura juntar o `Notification Pattern` com o `Rest Controller Advice`, se quisermos garantir que nenhum erro será perdido em um contexto de comunicação entre dois ou mais services.

Dessa forma, se formos introduzir o `Notification Pattern`, teremos que ser muito cuidados com a complexidade que isso trará. Talvez seja uma abordagem que fosse melhor ou "mergulhar de cabeça", abandonando o `Rest Controller Advice` e focando totalmente em "notificações" ao invés de exceções, ou não usar.

**Comment by FSLucas22** [comment]
> Dessa forma, se formos introduzir o `Notification Pattern`, teremos que ser muito cuidados com a complexidade que isso trará. Talvez seja uma ideia que é melhor ou "mergulhar de cabeça", abandonando o `Rest Controller Advice` e focando totalmente em "notificações" ao invés de exceções, ou não usar.

Um problema dessa abordagem, independente da implementação que se faça, é a incapacidade de retornar códigos HTTP específicos para cada caso, tudo necessitará ficar padronizado no mesmo código de erro.

Assim, não parece correto utilizar essa abordagem para validações de, por exemplo, existência de dados no banco, mas somente para casos em que a forma da um `request` é inválida, o que já fazemos utilizando o `Jakarta Validations`.

Dessa forma, somente para os casos em que é necessário realizar validações de formato de `request` que não sejam facilmente implementadas através do `Jakarta Validations` é que faria sentido utilizar o `Notification Pattern`. Mas essa necessidade não surgiu, até o momento, no projeto.

Por esse motivo entendo que a proposta dessa issue não deve ser implementada.
