### ISSUE TITLE
Criação de Testes Unitários e Integrados

### ISSUE THREAD

**Issue by hywenklis** [hywenklis/buddy-api#45]
## Descrição

Precisamos criar testes unitários e integrados para garantir a qualidade e confiabilidade do código, bem como para alcançar uma cobertura de testes satisfatória. Estes testes devem cobrir os principais cenários de uso e casos extremos, garantindo que todas as funcionalidades funcionem conforme o esperado.

## Objetivos

1. **Testes Unitários:**
   - Escrever testes unitários para todos os métodos e funções principais.
   - Garantir que cada unidade de código (método/função) funcione isoladamente.

2. **Testes Integrados:**
   - Escrever testes integrados que validem a interação entre diferentes componentes do sistema.
   - Garantir que a integração entre diferentes módulos esteja funcionando corretamente.

## Cenários de Teste

Os seguintes cenários de teste devem ser considerados:

1. **Cenários Positivos:**
   - Verificar que o comportamento esperado ocorre para entradas válidas.

2. **Cenários Negativos:**
   - Verificar o comportamento do sistema para entradas inválidas ou inesperadas.

3. **Casos Extremos:**
   - Testar limites superiores e inferiores de entradas.

4. **Fluxos Alternativos:**
   - Verificar comportamentos alternativos e exceções.

## Tarefas

- [ ] Identificar componentes/módulos que precisam de testes.
- [ ] Escrever testes unitários para cada componente/módulo identificado.
- [ ] Escrever testes integrados para verificar a interação entre os componentes.
- [ ] Configurar ferramentas de cobertura de testes e garantir que a cobertura atinja os padrões definidos.

## Critérios de Aceitação

- Testes unitários e integrados escritos e revisados.
- Cobertura de teste adequada (definir um percentual mínimo, se necessário).
- Nenhum bug crítico encontrado durante a execução dos testes.

## Notas Adicionais

Qualquer dúvida ou problema encontrado durante a criação dos testes deve ser discutido na seção de comentários desta issue.

---

**Autor:** @hywenklis 
**Data de Criação:** 14/07/2024

**Comment by FSLucas22** [comment]
Olhando pelo coverage do `Intellij`, parece mandatório testar o `FindPetController`, visto ser uma funcionalidade central do projeto que está com uma `coverage` extremamente baixa.

![image](https://github.com/user-attachments/assets/1131208f-0621-47fb-b6f8-80e3c4179c3e)

Os testes de integração são importantes pois garantem o funcionamento da aplicação em um nível mais próximo da forma como ele seria utilizado pelos usuários. Nesse sentido, são até mais importantes que os teste unitários, embora esses também não podem ser negligenciados.

Em seguida, o service `FindPetImpl` também necessita de testes para melhorar sua confiabilidade.

![image](https://github.com/user-attachments/assets/65981d81-6430-4916-b1c8-f6085d56dc75)

Por último, `PetSpecifications` também é importante que seja testada, embora os testes de integração no endpoint `GET /v1/pets` certamente já ajudarão na coverage dessa classe.

![image](https://github.com/user-attachments/assets/4f3db2f4-1dcd-475f-99a1-6312902e4e03)

**Comment by hywenklis** [comment]
Conforme alinhado todas as tarefas terão que ter testes unitários e integrados, assim aumentamos nossa cobertura de testes, dando mais confiabilidade em adição, remoção e refatoração do nosso código.
