### ISSUE TITLE
Endpoint "/pets" não faz sort por createdAt

### ISSUE THREAD

**Issue by genesluna** [hywenklis/buddy-api#48]
Ao fazer uma consulta com sort baseado na propriedade createdAt, o servidor retorna o seguinte erro:

>There was an unexpected error (type=Internal Server Error, status=500).
>No property 'createdAt' found for type 'PetEntity'

### Comportamento esperado
Retornar a lista de animais ordenada pela data de criação.

### Passos para reproduzir
Chamar o endpoint passando como argumento de ordenação a propriedade createdAt, como a seguir:
[https://buddy.propresto.app/api/v1/pets?&size=8&sort=createdAt,asc](https://buddy.propresto.app/api/v1/pets?&size=8&sort=createdAt,desc)

### Contexto
Gostaria de poder ordenar os animais em ordem de criação para poder mostrar os registros mais novos primeiro.

**Comment by hywenklis** [comment]
Analisando e dando andamento @genesluna.

**Comment by genesluna** [comment]
Bom dia. Continuo recebendo um erro quando tento fazer o sort por createdAt. Um erro diferente: 

````json
{
"errors": [
    {
        "field": "createdAt",
        "message": "An error occurred while searching for pets due to an invalid property reference",
        "httpStatus": "BAD_REQUEST",
        "errorCode": 400,
        "timestamp": "2024-08-20 09:03:00"
    }
  ]
}
````

Mas ainda é um erro. Notei que o padrão agora é fazer o sort por ````createdAt```` do mais novo para o mais antigo quando não há um método de ordenamento fornecido. Entretanto, gostaria de ter o poder de fazer essa escolha no cliente. Entendo se não for uma prioridade agora.

**Comment by hywenklis** [comment]
> Bom dia. Continuo recebendo um erro quando tento fazer o sort por createdAt. Um erro diferente:
> 
> ```json
> {
> "errors": [
>     {
>         "field": "createdAt",
>         "message": "An error occurred while searching for pets due to an invalid property reference",
>         "httpStatus": "BAD_REQUEST",
>         "errorCode": 400,
>         "timestamp": "2024-08-20 09:03:00"
>     }
>   ]
> }
> ```
> 
> Mas ainda é um erro. Notei que o padrão agora é fazer o sort por `createdAt` do mais novo para o mais antigo quando não há um método de ordenamento fornecido. Entretanto, gostaria de ter o poder de fazer essa escolha no cliente. Entendo se não for uma prioridade agora.

Bom dia @genesluna, tudo bem? Esse erro estava sendo causado pela exceção PropertyReferenceException, que era lançada ao não encontrar as propriedades de ordenação especificadas na entidade. Quando isso acontecia, o sistema retornava um erro 500, o que não era o comportamento ideal. O problema principal não estava no campo em si, mas sim na ausência de um tratamento adequado para propriedades de ordenação inexistentes, o que resultava na falha.

Esse problema foi corrigido, e agora, quando uma propriedade de ordenação não é encontrada, o sistema retorna uma mensagem de erro 400, informando claramente que a propriedade não existe. Um exemplo disso  é o campo de data de criação, que esta sendo referenciado como **createdAt**, mas o nome correto mapeado atualmente é **createDate**. Assim, ao tentar ordenar pela propriedade createdAt, o sistema informa que essa propriedade não existe...

Além disso, caso a requisição não especifique nenhuma propriedade de ordenação ou a direção (asc ou desc), o sistema aplica, por padrão, a ordenação pelo campo createDate em ordem descendente (desc).

Atualmente, o endpoint permite ordenação por qualquer propriedade válida da entidade Pet, e o cliente pode especificar a direção da ordenação. Um exemplo de uso seria:
```/pets?page=0&size=10&sort=createDate,desc```

Neste exemplo, a listagem dos pets será ordenada pela data de criação em ordem decrescente, mas outras propriedades de ordenação existentes também podem ser utilizadas conforme a necessidade.

Poderia tentar novamente com a utilização do nome **createDate** e nos da um feedback? Se for o caso de utilizar createAt, vai ser necessário mudar o atributo da tabela Pet.

**Comment by genesluna** [comment]
> Poderia tentar novamente com a utilização do nome **createDate** e nos da um feedback? Se for o caso de utilizar createAt, vai ser necessário mudar o atributo da tabela Pet.

@hywenklis Perfeito. Não me importa se é **createdAt** ou se é **createDate**. O importante é que tá funcionando. Valeu! Vou fechar a issue.
