### ISSUE TITLE
Corrigir mensagens de erro das validações do Jakarta nas requisições

### ISSUE THREAD

**Issue by FSLucas22** [hywenklis/buddy-api#81]
Atualmente as mensagens de erro de `campos obrigatórios` nas requisições estão nesse formato: `[nome do campo] of mandatory [entidade]`
O que dá a entender que a `entidade` é obrigatória, e não o `campo`.
Exemplos desses casos com as sugestões de correção:

https://github.com/hywenklis/buddy-api/pull/77#pullrequestreview-2215583878

Entendo que essa correção não deve ser feita no mesmo contexto da `feature de avatar` do `pet`, ou da `feature de state` do cadastro do pet, pois possui um escopo próprio independente destes assuntos, razão pela qual abri uma `issue` especifica para aplicar as correções sugeridas.

**Comment by hywenklis** [comment]
Não entendi o motivo! Analisando o código vejo que está explícito que se trata do campo. Poderia mostrar com mais detalhes o que teríamos que mudar?

**Comment by genesluna** [comment]
@hywenklis é que as mensagens de erro estão semanticamente incorretas em inglês. Segue alguns exemplos de como as mensagens estão: 

```java
@NotBlank(message = "Description of mandatory pet")
@NotBlank(message = "Avatar of mandatory pet")
@NotNull(message = "ShelterId of mandatory pet")
```

O correto seria:

"Mandatory pet description" ou "Pet description is mandatory"
"Mandatory pet avatar" ou "Pet avatar is mandatory"
"Mandatory pet ShelterId" ou "Pet ShelterId is mandatory"

Da forma como está, a tradução seria mais ou menos a seguinte:

"Descrição do pet obrigatório"
"Avatar do pet obrigatório"
"ShelterId do pet obrigatório"

Traduzido para português parece não haver diferença, mas o entendimento em inglês é que o "pet" é obrigatório e não o campo.

**Comment by hywenklis** [comment]
Obrigado pela explicação @genesluna, agora entendo o motivo e concordo que faz total sentido a mudança!

**Comment by hywenklis** [comment]
Issue resolvida pessoal @genesluna @FSLucas22
